version: '3.8'

services:
  # SGBD utilizado pela aplicação e pelo Keycloak
  database:
    image: mysql:8.0.30-debian
    restart: always
    environment:
      -  MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - "./volumes/mysql-data:/var/lib/mysql"

  # Solução de acesso à base de dados
  # Para acessar, utilize o usuário e senha disponibilizado através do endereço http://localhost:8081
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8081:8080
    environment:
      - ADMINER_DESIGN=nette