version: '3.8'

services:
  # SGBD utilizado pela aplicação
  db:
    image: mysql:8.0.30-debian
    restart: always
    environment:
      -  MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - "mysql-data:/var/lib/mysql"
      - "./volumes/db:/docker-entrypoint-initdb.d"


  # Solução de acesso à base de dados
  # Para acessar, utilize o usuário e senha disponibilizado através do endereço http://localhost:8081
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080
    environment:
      - ADMINER_DESIGN=dracula

  app:
    image: spmercantil/webapi
    build:
      args:
        progress: plain
      context: SpMercantil
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=SP_MERCANTIL;uid=sp_mercantil_app;password=laNtatEPIlentAtRUCKOdi
      - LOG_PATH="/tmp/SpMercantil/logs.txt"
  
  import:
    image: spmercantil/import
    build:
      context: import-data
      dockerfile: ./Dockerfile
    depends_on:
      - db
    volumes:
      - "./volumes/import:/import/data"
    environment:
      - DB_HOST=db
      - DB_USER=sp_mercantil_app
      - DB_PWD=laNtatEPIlentAtRUCKOdi
      - DB_DATABASE=SP_MERCANTIL

volumes:
  mysql-data:
