version: '3.8'

services:
  # SGBD utilizado pela aplicação
  db:
    image: mysql:8.0.30-debian
    restart: always
    environment:
      -  MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - "mysql-data:/var/lib/mysql"
      - "./volumes/db:/docker-entrypoint-initdb.d"


  # Solução de acesso à base de dados
  # Para acessar, utilize o usuário e senha disponibilizado através do endereço http://localhost:8081
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080
    environment:
      - ADMINER_DESIGN=dracula

  app:
    image: quarkus/spmercantil
    build:
      args:
        progress: plain
      context: spmercantil
      dockerfile: ./src/main/docker/Dockerfile.jvm
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DB_USERNAME=sp_mercantil_app
      - DB_PASSWORD=laNtatEPIlentAtRUCKOdi
      - DB_URL=jdbc:mysql://db:3306/SP_MERCANTIL
  
  import:
    image: quarkus/import
    build:
      context: import-data
      dockerfile: ./Dockerfile
    depends_on:
      - db
    volumes:
      - "./volumes/import:/import/data"
    environment:
      - DB_HOST=db
      - DB_USER=sp_mercantil_app
      - DB_PWD=laNtatEPIlentAtRUCKOdi
      - DB_DATABASE=SP_MERCANTIL

volumes:
  mysql-data:
